#9 faça um programa que leia o seu numero e fale a tabuada do mesmo

tab = int(input('Digite um numero e descubra a tabuada: '))
print('-' *12)
print('{} x {:2} = {}'.format(tab,1, tab * 1))
print('{} x {:2} = {}'.format(tab,2, tab * 2))
print('{} x {:2} = {}'.format(tab,3, tab * 3))
print('{} x {:2} = {}'.format(tab,4, tab * 4))
print('{} x {:2} = {}'.format(tab,5, tab * 5))
print('{} x {:2} = {}'.format(tab,6, tab * 6))
print('{} x {:2} = {}'.format(tab,7, tab * 7))
print('{} x {:2} = {}'.format(tab,8, tab * 8))
print('{} x {:2} = {}'.format(tab,9, tab * 9))
print('{} x {:2} = {}'.format(tab,10, tab * 10))
print('-' *12)
